backend:
  name: git-gateway
  branch: main
media_folder: "static/images" # Folder where user uploaded files should go
public_folder: "images"
collections:
  - name: "settings"
    label: "Settings"
    files:
      - file: "content/settings/_index.md"
        label: "Info"
        name: "info"
        fields:
          - { label: "Name", name: "name", widget: "string" }
          - { label: "Address Line 1", name: "address1", widget: "string" }
          - { label: "Address Line 2", name: "address2", widget: "string" }
          - { label: "Email", name: "email", widget: "string" }
          - { label: "Phone", name: "phone", widget: "string" }
  - name: "content"
    label: "Content"
    files:
      - file: "content/photoarchive/_index.md"
        label: "Photo Archive"
        name: "photoarchive"
        fields:
          - label: "Photos"
            name: "photos"
            widget: "list"
            summary: "{{fields.date}}"
            fields:
              - { label: "Date", name: "date", widget: "string" }
              - { label: "Image File", name: "imagefile", widget: "image" }