backend:
  name: git-gateway
  branch: main
media_folder: "static/images" # Folder where user uploaded files should go
public_folder: "images"
collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "content/_index.md"
        label: "Home"
        name: "home"
        fields:
          - { label: "Page Title", name: "pagetitle", widget: "string" }
          - {
              label: "Page URL",
              name: "pageurl",
              widget: "string",
              required: false,
            }
          - { label: "Nav Item", name: "navitem", widget: "boolean" }
          - { label: "Subhead", name: "subhead", widget: "string" }
          - { label: "Bio", name: "bio", widget: "markdown" }
          - label: "Background"
            name: "background"
            widget: "object"
            fields:
              - {
                  label: "Background Placeholder",
                  name: "bgplaceholder",
                  widget: "image",
                }
          - label: "Bio Links"
            name: "biolinks"
            widget: "list"
            summary: "{{fields.linktitle}}"
            fields:
              - { label: "Link Title", name: "linktitle", widget: "string" }
              - { label: "Link URL", name: "linkurl", widget: "string" }
      - file: "content/photo/_index.md"
        label: "Photo"
        name: "photo"
        fields:
          - { label: "Page Title", name: "pagetitle", widget: "string" }
          - { label: "Page URL", name: "pageurl", widget: "string" }
          - { label: "Nav Item", name: "navitem", widget: "boolean" }
          - { label: "Subhead", name: "subhead", widget: "string" }
          - label: "Photo Projects"
            name: "photoprojects"
            widget: "list"
            summary: "{{fields.projecttitle}}"
            fields:
              - {
                  label: "Project Title",
                  name: "projecttitle",
                  widget: "string",
                }
              - label: "Images"
                name: "images"
                widget: "list"
                summary: "{{fields.caption}}"
                fields:
                  - { label: "Caption", name: "caption", widget: "string" }
                  - { label: "Image File", name: "imagefile", widget: "image" }
      - file: "content/productdesign/_index.md"
        label: "Product Design"
        name: "productdesign"
        fields:
          - { label: "Page Title", name: "pagetitle", widget: "string" }
          - { label: "Page URL", name: "pageurl", widget: "string" }
          - { label: "Nav Item", name: "navitem", widget: "boolean" }
          - { label: "Subhead", name: "subhead", widget: "string" }
          - { label: "Intro", name: "intro", widget: "markdown", required: false }
          - label: "Projects"
            name: "projects"
            widget: "list"
            summary: "{{fields.client}}"
            fields:
              - { label: "Client", name: "client", widget: "string" }
              - { label: "Description", name: "desc", widget: "string" }
              - label: "Images"
                name: "images"
                widget: "list"
                summary: "{{fields.imagefile}}"
                fields:
                  - { label: "Image File", name: "imagefile", widget: "image" }
          - label: "Bio Links"
            name: "biolinks"
            widget: "list"
            summary: "{{fields.linktitle}}"
            fields:
              - { label: "Link Title", name: "linktitle", widget: "string" }
              - { label: "Link URL", name: "linkurl", widget: "string" }
